name: Docker build check

on:
  workflow_dispatch:
  
  pull_request:
  
jobs:

  build-and-push-image:
  
    runs-on: ubuntu-latest
    
    env:
      REGISTRY: ghcr.io
      USER: ${{ github.actor }}
      REPOSITORY: ${{ github.repository }}
      PAT: ${{ secrets.GITHUB_TOKEN }}
      VERSION: ${{ github.sha }}
      IP: ${{ secrets.IP }}
      HOST: ${{ secrets.HOST }}
      KNWHST: ${{ secrets.KNWHST }}
      PWD: ${{ secrets.PWD }}
      PORT: ${{ secrets.PORT }}
      CNTNR_PRT_IN: ${{ secrets.CNTNR_PRT_IN }}
      CNTNR_PRT_OT: ${{ secrets.CNTNR_PRT_OT }}
      CNTNR_NM: ${{ secrets.CNTNR_NM }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Build Image
        run: 
          docker build -t ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.VERSION }} .
