name: Build and deploy rdi

on:
  pull_request:
    branches: 
      - main
  workflow_dispatch:
  
jobs:

  build-and-push-image:
  
    runs-on: ubuntu-latest
    
    env:
      REGISTRY: ghcr.io
      USER: ${{ github.actor }}
      REPOSITORY: ${{ github.repository }}
      PAT: ${{ secrets.GITHUB_TOKEN }}
      VERSION: ${{ github.sha }}
      IP: ${{ secrets.ip }}
      HOST: ${{ secrets.user }}
      KNWHST: ${{ secrets.knwhst }}
      PWD: ${{ secrets.pwd }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Build Image
        run: 
          docker build -t ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.VERSION }} .

      - name: Log in to the GHCR
        run: 
          echo $PAT | docker login ghcr.io -u $USER --password-stdin
          
      - name: Push image to the GHCR
        run: 
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.VERSION }}
          
      - name: Deploy new image
        run:
          ssh -i ${{ env.PWD }} ${{ env.USER }}@${{ env.IP }} && sudo docker rm -f react_main && sudo docker run -d -p 80:80 --name react_main ghcr.io/inscannr/w-app:${{ env.VERSION }} 
