name: Build and deploy rdi

on:
  push:
    branches: 
      - main
  
jobs:

  build-and-push-image:
  
    runs-on: ubuntu-latest
    
    env:
      REGISTRY: ghcr.io
      USER: ${{ github.actor }}
      REPOSITORY: ${{ github.repository }}
      PAT: ${{ secrets.GITHUB_TOKEN }}
      VERSION: ${{ github.sha }}
      IP: ${{ secrets.IP }}
      HOST: ${{ secrets.HOST }}
      KNWHST: ${{ secrets.KNWHST }}
      PWD: ${{ secrets.PWD }}
      PORT: ${{ secrets.PORT }}
      CNTNR_PRT_IN: ${{ secrets.CNTNR_PRT_IN }}
      CNTNR_PRT_OT: ${{ secrets.CNTNR_PRT_OT }}
      CNTNR_NM: ${{ secrets.CNTNR_NM }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Build Image
        run: 
          docker build -t ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.VERSION }} .

      - name: Log in to the GHCR
        run: 
          echo $PAT | docker login ghcr.io -u $USER --password-stdin
          
      - name: Push image to the GHCR
        run: 
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.VERSION }}
          
      - name: Deploy
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with:
          host: ${{ env.IP }}
          user: ${{ env.HOST }}
          key: ${{ env.PWD }}
          first_ssh: sudo docker rm -f ${{ env.CNTNR_NM }}
          last_ssh: sudo docker run -d -p ${{ env.CNTNR_PRT_OT }}:${{ env.CNTNR_PRT_IN }} --name ${{ env.CNTNR_NM }} ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.VERSION }}
