name: Build and deploy rdi

on:
  pull_request:
    branches: 
      - main
  workflow_dispatch:
  
jobs:

  build-and-push-image:
  
    runs-on: ubuntu-latest
    
    env:
      REGISTRY: ghcr.io
      USER: ${{ github.actor }}
      REPOSITORY: ${{ github.repository }}
      PAT: ${{ secrets.GITHUB_TOKEN }}
      VERSION: ${{ github.sha }}
      IP: ${{ secrets.IP }}
      HOST: ${{ secrets.HOST }}
      KNWHST: ${{ secrets.KNWHST }}
      PWD: ${{ secrets.PWD }}
      PORT: ${{ secrets.PORT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Build Image
        run: 
          docker build -t ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.VERSION }} .

      - name: Log in to the GHCR
        run: 
          echo $PAT | docker login ghcr.io -u $USER --password-stdin
          
      - name: Push image to the GHCR
        run: 
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.VERSION }}
          
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ env.IP }}
          username: ${{ env.HOST }}
          key: ${{ env.PWD }}
          port: ${{ env.PORT }}
          script: |
            sudo docker rm -f react_main
            sudo docker run -d -p 80:80 --name react_main ghcr.io/inscannr/w-app:${{ env.VERSION }}
    
